DROP DATABASE IF EXISTS users;

CREATE DATABASE IF NOT EXISTS users;

use users;

CREATE TABLE IF NOT EXISTS listado_usuarios  (
    id INT (11) AUTO_INCREMENT,
    nombre VARCHAR(100) NOT NULL,
    apellidos VARCHAR(100) NOT NULL,
    correo VARCHAR(100) NOT NULL,
    passwd VARCHAR(100) NOT NULL,
    PRIMARY KEY (id)
) ENGINE=INNODB;