DROP DATABASE IF EXISTS users;

CREATE DATABASE IF NOT EXISTS users;

use users;

CREATE TABLE IF NOT EXISTS listado_usuarios  (
    id INT (11) AUTO_INCREMENT,
    user VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL,
    PRIMARY KEY (id)
) ENGINE=INNODB;